# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.
include: "rules/common.smk"

singularity: config["sif_path"]

CHROMOSOMES = [f"chr{i:02d}" for i in range(1, 13)]

rule all:
    input:
        expand("results/vcf/all.{chrom}.vcf.gz", chrom=CHROMOSOMES),
        expand("results/all.snp.final.vcf.gz"),
        expand("results/all.indel.final.vcf.gz")
##### Modules #####

include: "rules/ref.smk"
include: "rules/mapping.smk"
include: "rules/calling.smk"
include: "rules/filter.smk"
